### ISSUE TITLE
[勘误]反馈一个第1章第3.3节的流程图

### ISSUE THREAD

**Issue by Kimgtb** [RainbowMango/GoExpertProgramming#103]
<img width="184" alt="image" src="https://user-images.githubusercontent.com/8787046/204120433-a1fa9213-8d21-4b9a-845a-46d091992d1c.png">
从buf队首取出数据，再从sendq取出一个G，图片红框应该是把数据写入到G吧？然后唤醒g，而不是又把G的数据写入到队尾，难道是带着数据来的G？

谢谢

**Comment by Kimgtb** [comment]
已了解

**Comment by RainbowMango** [comment]
嗯。带缓冲区的channel读取时是从缓冲区读的。

好像问题已解决，先关闭了。
