### ISSUE TITLE
[勘误]反馈一个第一章第2节的错别字

### ISSUE THREAD

**Issue by ma-xiaoba** [RainbowMango/GoExpertProgramming#106]
**问题描述**
![image](https://github.com/RainbowMango/GoExpertProgramming/assets/49982384/bd7d1115-3527-487e-a75b-058c89b5591f)
位置：第一章->1.2 Slice -> 3.5特殊切片
这里的对最后一个值的解读不太对，最后一个值应该是max。还有新切片的容量应该是cap = max - low；

------------------
这是我从网上找的一本PDF，不确实最新版本或者纸质书里面有没有这个问题

**Comment by RainbowMango** [comment]
感谢反馈，这个内容应该出自还没出版前的版本，纸质书已经没有相关内容。

PS：网上的PDF版本并没有同步后续的勘误，我也不知道如何联系相关人处理 :(

不过仍然感谢。
