### ISSUE TITLE
[勘误]反馈一个第3章第1节的错别字

### ISSUE THREAD

**Issue by DessertHeart** [RainbowMango/GoExpertProgramming#108]
**问题描述**
第三段，"协程调度器把可运行的协程逐个调度到线程中执行，同时及时把阻塞的协程调度出**协程**"

**如何找到这个错误**
- 章节：3.1
- 页码：96
（第2版）

**您认为应该如何？**

应该是**线程**？

**其他补充信息**

**Comment by DessertHeart** [comment]
补：反馈一个第4章第1节的配图问题

章节：4.1
页码：110
（第2版）

mheap管理内存示意图：bitmap的箭头指向位置错误(指向了bitmap**末尾地址**)？

应该指向bitmap**起始地址**？

**Comment by DessertHeart** [comment]
补：反馈一个第4章第1节的单词拼写错误

章节：4.1
页码：111
（第2版）

第一段：系统预分配内存分为spans、bitmap、**arean**...

单词arean应为**arena**

**Comment by RainbowMango** [comment]
感谢反馈。

> 第三段，"协程调度器把可运行的协程逐个调度到线程中执行，同时及时把阻塞的协程调度出协程"

这个问题已修正：https://github.com/cloudnativebooks/cloud-native-go/issues/8。
（有点奇怪，这是2020年修改的内容，竟然第二版还存在，很可能是出版社编辑忘记同步，待确认）

**Comment by RainbowMango** [comment]
确认了，是我忘记同步给出版社编辑了。下次印刷时更新吧。谢谢反馈。

**Comment by RainbowMango** [comment]
> mheap管理内存示意图：bitmap的箭头指向位置错误(指向了bitmap末尾地址)？

记得当初画这个图时参考的代码是1.9版本的，代码在此：https://github.com/golang/go/blob/c8aec4095e089ff6ac50d18e97c3f46561f14f48/src/runtime/mheap.go#L111C41-L111C46

不过，新版本该数据结构已更新，没有bitmap了。

图书再版时更新吧。（个人觉得这个内容无关紧要，可能会删除该章节）

**Comment by RainbowMango** [comment]
> 第一段：系统预分配内存分为spans、bitmap、arean...
单词arean应为arena

已修改。将在第二版第三次印刷时更新。

**Comment by RainbowMango** [comment]
再次感谢勘误，如有新的问题请另开一个issue，感谢~
