### ISSUE TITLE
[疑问]第二章for range

### ISSUE THREAD

**Issue by txbxxx** [RainbowMango/GoExpertProgramming#109]
**问题描述**
```go
func main() {
	s := []int{1,2,3}
	var wg sync.WaitGroup
	wg.Add(len(s))
	for _,v := range s {
		go func ()  {
			fmt.Println(v)
			wg.Done()
		}()
	}
	wg.Wait()
}
```

**如何找到这个错误**
- 章节：2
- 页码：85

**您认为应该如何？**

这里应该是随机输出1 2 3 的顺序而不是3个3吧

**图片**
如果有可能，尽量提供图片。

**其他补充信息**

**Comment by RainbowMango** [comment]
你说得对。我猜你用的Go版本应该是 v1.22+。 在v1.21及之前的版本中，大概率是输出3个3。在v1.22中官方优化了这个问题。for 循环中的变量将不会共享。

详见Release Notes: https://go.dev/doc/go1.22
> Previously, the variables declared by a “for” loop were created once and updated by each iteration. In Go 1.22, each iteration of the loop creates new variables, to avoid accidental sharing bugs. The [transition support tooling](https://go.dev/wiki/LoopvarExperiment#my-test-fails-with-the-change-how-can-i-debug-it) described in the proposal continues to work in the same way it did in Go 1.21.

**Comment by RainbowMango** [comment]
感谢提醒，这个题目已经从最新的书稿中删除了，后面重印时体现。

**Comment by txbxxx** [comment]
谢谢您，请问您有准备出云开发或者云相关的书籍嘛 👍

**Comment by RainbowMango** [comment]
暂时没有计划
