### ISSUE TITLE
[疑问]反馈一个第5章第4节的解锁并唤醒协程

### ISSUE THREAD

**Issue by txbxxx** [RainbowMango/GoExpertProgramming#110]
**问题描述**
在mutex A解锁唤醒B并加锁的时候woken是不是应该为1

**如何找到这个错误**
- 章节：5
- 页码：146

**您认为应该如何？**

**图片**

![image](https://github.com/user-attachments/assets/acb3c3c8-dcff-4760-8335-966d64b40749)

**其他补充信息**

**Comment by txbxxx** [comment]
嗷，不好意思是我理解错了意思

**Comment by RainbowMango** [comment]
没关系，我也重新审视了一下这个章节。也同样感谢~
