### ISSUE TITLE
[勘误]panic为nil使用recover

### ISSUE THREAD

**Issue by txbxxx** [RainbowMango/GoExpertProgramming#111]
**问题描述**
在书中描述: panic为nil ，`recover`捕获的值还是为`nil`
可能是在新版本中有改动我使用的是1.25.5，recover捕获panic(nil) 的值为：`panic called with nil argument`

**如何找到这个错误**
- 章节：8
- 页码： 264

**您认为应该如何？**

**图片**
![ae7c93eb674a3052e6eac0c33e28190](https://github.com/user-attachments/assets/ec680d42-adcc-4cd1-9c84-84555b5e15c9)

**其他补充信息**

**Comment by RainbowMango** [comment]
好的，我回头确认一下。

> 可能是在新版本中有改动我使用的是1.25.5

当前Golang最新版本为go1.23.3，你是不是看错了？

**Comment by txbxxx** [comment]
> 好的，我回头确认一下。
> 
> > 可能是在新版本中有改动我使用的是1.25.5
> 
> 当前Golang最新版本为go1.23.3，你是不是看错了？

不好意思我使用的是`1.21.5`

**Comment by RainbowMango** [comment]
经确认，从[Go 1.21版本起 `panic(nil)`将会触发一种特殊的error](https://github.com/golang/go/blob/c96939fbed3d60159dc81ee9ad591de8cfd41168/src/builtin/builtin.go#L276-L279)，见如下描述：
```golang
// Starting in Go 1.21, calling panic with a nil interface value or an
// untyped nil causes a run-time error (a different panic).
// The GODEBUG setting panicnil=1 disables the run-time error.
func panic(v any)
```

经测试，这种error的描述为 `panic called with nil argument`。

我再想下如何修改这部分内容。

**Comment by RainbowMango** [comment]
这段内容拟修改为如下：
```
recover()函数用于阻断panic崩溃链，使程序恢复运行，同时还接收panic所传递的信息（即panic()函数的参数）并通过返回值返回。如果程序没有panic，则返回nil。

从Go 1.21版本起，如果panic()函数参数为nil，将会触发一种特殊的panic，此panic也可以被recover()函数捕获，
但返回值为 `panic called with nil argument`。

如下面代码所示，尽管panic()函数参数为 nil，但recover() 接收到的信息为 "panic called with nil argument"。
于是字符串"A"会被打印出来，同时消除panic，但字符串"B"不会被打印。
```
同时，示例代码增加部分注释如下：
```golang
func RecoverDemo6() {
	defer func() {
		if err := recover(); err != nil { // err 值不为 nil
			fmt.Println("A") // 正常打印
		}
	}()

	panic(nil) // 等同于 panic("panic called with nil argument")
	fmt.Println("B")
}
```

如有进一步意见请告知。谢谢！

**Comment by txbxxx** [comment]
谢谢您抽空修改

**Comment by RainbowMango** [comment]
真是太客气了，再次感谢反馈~修正内容将会在下次重印时体现。
