### ISSUE TITLE
[勘误]反馈一个第12章第12.3.3节

### ISSUE THREAD

**Issue by txbxxx** [RainbowMango/GoExpertProgramming#112]
**问题描述**
go.sum中的go指令指明了模块开发所用的版本如go.1.19

这里应该是go.mod 文件吧

**如何找到这个错误**
- 章节：12
- 页码：337

**您认为应该如何？**

**图片**
如果有可能，尽量提供图片。

**其他补充信息**

**Comment by RainbowMango** [comment]
> 这里应该是go.mod 文件吧

是的，感谢反馈~

我稍后会修改。

**Comment by RainbowMango** [comment]
已经在书稿中修改。感谢反馈。
