### ISSUE TITLE
7.3.3 节t.Run()的简化代码

### ISSUE THREAD

**Issue by marjune163** [RainbowMango/GoExpertProgramming#41]
https://github.com/RainbowMango/GoExpertProgramming/blob/master/chapter07/7.3.3-unit.md#%E5%90%AF%E5%8A%A8%E5%AD%90%E6%B5%8B%E8%AF%95run

testName是经过处理的name，但从简化代码看似乎是没有定义过。

**Comment by RainbowMango** [comment]
是的，回过头来看测试这个章节写得不够清楚，我来改一下。
