### ISSUE TITLE
建议加上50个坑系列

### ISSUE THREAD

**Issue by aleimu** [RainbowMango/GoExpertProgramming#57]
建议在附录里补充上新手50个坑，如[https://segmentfault.com/a/1190000013739000#](url)

**Comment by RainbowMango** [comment]
可以，可是你给的链接好像打不开

**Comment by RainbowMango** [comment]
我猜是这个：http://devs.cloudimmunity.com/gotchas-and-common-mistakes-in-go-golang/index.html

**Comment by aleimu** [comment]
是的，就是它，我发的链接直接点好像是不行，复制后跳转是可以的，就是那篇英文的翻译版。

**Comment by RainbowMango** [comment]
回头我仔细看下，看了前几个，都是编译器能发现的错误，叫坑么？

**Comment by RainbowMango** [comment]
后面的有点意思，似曾相识的感觉:)

**Comment by RainbowMango** [comment]
谢谢提供建议，后面会考虑加上些的
