### ISSUE TITLE
5.2 章节疑问 

### ISSUE THREAD

**Issue by sjsdfg** [RainbowMango/GoExpertProgramming#72]
**Add()操作必须早于Wait(), 否则会panic**

这个理论怎么来的？
```go
func main() {
	var wg sync.WaitGroup

	wg.Wait()
	wg.Add(2)
}
```

wo我这边尝试了一下没有得到任何 panic 啊

输出是正常的

![image](https://user-images.githubusercontent.com/8037152/88154614-aa43e580-cc39-11ea-82c3-a42c7b956741.png)

**Comment by RainbowMango** [comment]
明天细看一下啊，你用的哪个版本？

**Comment by sjsdfg** [comment]
> 明天细看一下啊，你用的哪个版本？

1.14,

感觉就是这一句话的表述有问题。

你这个的意思应该表述的是避免让 state 出现负值，出现负值会触发 panic。但是结论的 tip 和前面表述的完全不是一个意思。

**Comment by RainbowMango** [comment]
谢谢提醒，这里想表达的是：Add()操作要早于`Done()`，否则会panic。

**Comment by sjsdfg** [comment]
> 谢谢提醒，这里想表达的是：Add()操作要早于`Done()`，否则会panic。

无法理解和认同，随便写个例子就已经证明这句话是错的
