### ISSUE TITLE
关于2020.07第一版 《Go专家编程》 P75 题目四，答案(P77)描述错误

### ISSUE THREAD

**Issue by xiaolulua** [RainbowMango/GoExpertProgramming#76]

**Comment by xiaolulua** [comment]
答案中所解析出的答案为C选项，但最后在答案解析结尾说“本题答案为D”

**Comment by RainbowMango** [comment]
感谢 @xiaolulua 反馈，确实如此。

@marjune163 在https://github.com/cloudnativebooks/cloud-native-go/issues/7 里也提到了。

PS：书稿中是没有显式的给出答案的，可能在编辑过程中出版社写错了。这个问题将在下次印刷时修改掉。

**Comment by RainbowMango** [comment]
@xiaolulua 有没有其他的建议或者你认为本书对你是否有帮助？

**Comment by xiaolulua** [comment]
好的呢，这本书写的很好呀，鞭辟入里的同时也通俗易懂，是中文参考资料中为数不多对Go系统且深入解析的书籍。首版难免有印刷错误嘛，书还没读完，将会继续阅读。PS：刚从C++转入Go，真的很喜欢这种讲解内部机理的书，读题来让人很舒心，不再会有浮沙筑高台的恐慌。十分感谢作者的付出！

**Comment by RainbowMango** [comment]
感谢鼓励和支持。

我也是从C/C++转的Go~~

**Comment by wide288** [comment]
书写的非常好，问题答案还是有显式答案感觉更方便。现在并不是都有。有的感觉怪了点，不过问题的答案说明非常好。

**Comment by RainbowMango** [comment]
> 书写的非常好，问题答案还是有显式答案感觉更方便。现在并不是都有。有的感觉怪了点，不过问题的答案说明非常好。

我当初的想法是统一不写答案，是编辑看完以后加的:)  后面有机空把没答案的都补上。

**Comment by yugu2day** [comment]
@RainbowMango 目前在看第二版（2023年4月第1次印刷）， 这个问题在 P84 和 P86 依然存在
![1](https://github.com/RainbowMango/GoExpertProgramming/assets/18064862/4d90c794-bda4-4903-ae94-7a712e975628)
![2](https://github.com/RainbowMango/GoExpertProgramming/assets/18064862/3fbd60a6-2777-41bf-8308-e94a0c7d639d)

**Comment by RainbowMango** [comment]
这个问题我跟编辑同步一下，编辑那边的版本没修改~，暂时打开Issue继续跟踪。谢谢提醒，有心了~

**Comment by RainbowMango** [comment]
得到编辑确认，已经修改了。再次感谢提醒和关注。
