### ISSUE TITLE
[勘误]反馈一个第2章第2节的错别字

### ISSUE THREAD

**Issue by qzqsmile** [RainbowMango/GoExpertProgramming#78]
**问题描述**
“由于string底层使用 Unicode 编码方式,字符可能占用1-4个字节”，

**如何找到这个错误**
- 章节：2.2.2特性预览
- 页码：P78

**您认为应该如何？**

应该是UTF8

**图片**
如果有可能，尽量提供图片。

**其他补充信息**

**Comment by qzqsmile** [comment]
我的理解有误, -.-!

**Comment by RainbowMango** [comment]
没关系
