### ISSUE TITLE
请教下移除timer为何采用四叉堆实现呢 ?

### ISSUE THREAD

**Issue by 0xc9e36** [RainbowMango/GoExpertProgramming#8]
```
type runtimeTimer struct {
	tb uintptr
	i  int

	when   int64
	period int64
	f      func(interface{}, uintptr) // NOTE: must not be closure
	arg    interface{}
	seq    uintptr
}
```

用数组实现, 移除(还未过期)的时候可以直接根据数组下标定位到对应的堆元素, 时间复杂度 O(1),  然后调整堆顺序 O(lgN) 

我有两个问题:
1. 为什么要用四叉堆呢? 
2. 如果不用数组实现的话, 移除元素有什么数据结构能达到 O(lgN) 的时间复杂度吗?

**Comment by RainbowMango** [comment]
> 为什么要用四叉堆呢?

首先，解释为什么使用堆？ 堆可以方便的对数据进行排序，其时间复杂度比较稳定，尤其是只关注最大、最小的场景。常见的是二叉堆，那么四叉堆的优点是降低了堆的高度，查找性能好一些，随叉数增加，实现复杂度也会提高，所以我个人理解，四叉是个权衡的结果。

> 如果不用数组实现的话, 移除元素有什么数据结构能达到 O(lgN) 的时间复杂度吗?

比较难，我们既想要排序，还要随时准备调整。
