### ISSUE TITLE
请问书中的讲解是基于golang哪个版本呢？

### ISSUE THREAD

**Issue by soooldier** [RainbowMango/GoExpertProgramming#81]
请问书中的讲解是基于golang哪个版本呢？

**Comment by RainbowMango** [comment]
这本书主要讲解Go语言本身的特性，大部分特性已经固化不会变动，小部分特性（比如Go Module）稍有变化，但底层原理还是不会变。所以，这本书跟语言版本不是那么强相关。

最终定稿时使用的是Go1.14.

**Comment by soooldier** [comment]
> 这本书主要讲解Go语言本身的特性，大部分特性已经固化不会变动，小部分特性（比如Go Module）稍有变化，但底层原理还是不会变。所以，这本书跟语言版本不是那么强相关。
> 
> 最终定稿时使用的是Go1.14.

感谢大神无私付出 🙏
