### ISSUE TITLE
可否在亚马逊上架电子版，目前，在海外很难看到这本书

### ISSUE THREAD

**Issue by daisuki-konbini** [RainbowMango/GoExpertProgramming#83]
**问题描述**

**如何找到这个错误**
- 章节：
- 页码：

**您认为应该如何？**

**图片**
如果有可能，尽量提供图片。

**其他补充信息**

**Comment by RainbowMango** [comment]
你好，来自海外的朋友:)

据我所知，出版社目前没有这方面的计划。
