### ISSUE TITLE
[内容优化] 图片形式

### ISSUE THREAD

**Issue by jiekun** [RainbowMango/GoExpertProgramming#84]
**问题描述**
Hi.
书看了一半有余，觉得内容都很独特新颖，感谢分享。

关于书中图片有一些小建议，目前（应该是）所有插图都是标量图，看起来都是在类似ProcessOn这类工具上画出来再保存(png | jpg等)下来，然后插入到正文中的，在阅读的时候就会发现图中的中英文、图形、箭头都有模糊不清。尽管没有影响到理解内容，但是观感上来说对图书而言还是觉得可以改善。

**您认为应该如何？**
插图使用矢量图。但是全书内容重新编辑可能工作量也比较大，不然的话陈晓猛老师应该也有考虑过这个问题，在出版前处理掉了。

**其他补充信息**
Ver: 2020年7月第一版第1次印刷。
最后感谢任老师的写作，内容很棒。

**Comment by RainbowMango** [comment]
首先感谢反馈，确实如此，使用ProcessOn这种工具确实有不清楚的图片。

关于矢量图，有什么工具推荐吗？重新画也可以的，可以在每次印刷时修改一部分。

**Comment by jiekun** [comment]
Hi.
感谢及时回复。个人没有什么熟悉的矢量图工具，不过觉得任老师可以问一下晓猛编辑，他们熟悉写作流程，应该会有很多相应的工具推荐 :)

**Comment by RainbowMango** [comment]
好的。

另外，如果发现哪些图片影响到了阅读，或者严重模糊的情况，还望及时告知，我好尽快修复。

**Comment by jiekun** [comment]
目前阅读了前8章，其实大部分图片都是一样，能明显看出来是标量图，但是图和文本还是能认得出来的，没有影响理解
