### ISSUE TITLE
[勘误] 反馈热身测验题目选项有误

### ISSUE THREAD

**Issue by jiekun** [RainbowMango/GoExpertProgramming#85]
**问题描述**
热身测验题目选项有误

**如何找到这个错误**
- 章节：第八章 / 8.2 defer / 8.2.1 热身测验 / 题目二
- 页码：227

**您认为应该如何？**
下面函数的输出结果是什么（单选）？
```
func DeferDemo2() {
        var aInt = 1

        defer fmt.Println(aInt)

        aInt = 2
        return
}
```
- A: 0
- B: 1

应改为：
- A: 2
- B: 1

**图片**
如果有可能，尽量提供图片。

**其他补充信息**

**Comment by RainbowMango** [comment]
确实如此。感谢。已在书稿中修改。
