### ISSUE TITLE
关于3.2G0系统调用描述问题探讨

### ISSUE THREAD

**Issue by XiaoyeFang** [RainbowMango/GoExpertProgramming#87]
**问题描述**
关于3.2G0系统调用描述问题探讨

![516BAF96-41EF-4951-A9C5-1BD0826D9670](https://user-images.githubusercontent.com/45748507/106882439-b5fc8280-6719-11eb-9b80-786d5def1ea0.jpg)

**如何找到这个错误**
- 章节：3
- 页码：

**您认为应该如何？**

这一小段是否描述为m0被系统调用更为合理，尽管本质上也是系统调用了G0，但描述上是否应该以m0视角出发
仅代表个人观点，如果说的不对的话还望见谅

**图片**
如果有可能，尽量提供图片。

**其他补充信息**

**Comment by RainbowMango** [comment]
> 这一小段是否描述为m0被系统调用更为合理，尽管本质上也是系统调用了G0，但描述上是否应该以m0视角出发

恩，有点道理。协程是应用层的实现，核心就是协程管理器明确知道哪些操作会阻塞线程。
