### ISSUE TITLE
[勘误]反馈一个第一章第二节中关于slice扩容问题

### ISSUE THREAD

**Issue by xs-cw** [RainbowMango/GoExpertProgramming#88]
**问题描述**
文中描述是基于go1.16之前版本扩容规则，1.16后扩容规则有所变动。题目举例已经不符合预期了。
```go
func main(){
 var slice []int
 slice = append(slice, 1, 2, 3)// 此时cap(slice)为3，go1.16前为4
}
```
**如何找到这个错误**
- 章节：
  `常见数据结构实现原理`中slice篇
- 页码：

**您认为应该如何？**

**图片**
如果有可能，尽量提供图片。

**其他补充信息**

**Comment by RainbowMango** [comment]
谢谢提醒，1.16的变化我还没来得及看。

**Comment by RainbowMango** [comment]
@xs-cw 请问你是看的1.16源码吗？扫了一遍 [1.16 release notes](https://golang.org/doc/go1.16) 没看到相关说明。

**Comment by xs-cw** [comment]
@RainbowMango  源码里有体现的，github上[地址](https://github.com/golang/go/commit/2333c6299f340a5f76a73a4fec6db23ffa388e97?branch=2333c6299f340a5f76a73a4fec6db23ffa388e97)

**Comment by RainbowMango** [comment]
```diff
关于下面函数的描述，正确的是？
 func SliceExtend() {
-       var slice []int
-       s1 := append(slice, 1, 2, 3)
+       s := make([]int, 0, 10)
+       s1 := append(s, 1, 2, 3)
        s2 := append(s1, 4)

        fmt.Println(&s1[0] == &s2[0])
 }
 单选：
-- A： 函数操作nil切片会panic
+- A： append函数在操作切片s和s1时发生了扩容
 - B： 编译错误，不可以对切片元素取址
 - C： 函数输出 true
 - D： 函数输出 false
```

感谢@lzw5399 @xs-cw 两位提供的信息，计划如上修订。题目不再考察扩容的细节。

**Comment by RainbowMango** [comment]
修订将提供给出版社，不出意外会在第4次印刷地修订。欢迎继续指正。

**Comment by RainbowMango** [comment]
> @RainbowMango 源码里有体现的，github上[地址](https://github.com/golang/go/commit/2333c6299f340a5f76a73a4fec6db23ffa388e97?branch=2333c6299f340a5f76a73a4fec6db23ffa388e97)

@xs-cw 又仔细看了你列出的这个改动。
这个改动主要是解决`append(s, 0, 0)` 和 `append(append(s,0), 0)` 这两个表达的行为差异。

它解释不了下面的代码行为：
```
// main.go
package main

import "fmt"

func main() {
	var slice []int
	s1 := append(slice, 1, 2, 3)
	fmt.Println(cap(s1))
}
```
上面代码在Go1.15中返回`4`, 在Go1.16中返回`3`。
不管在Go1.15还是在Go1.16中，上面代码中的`append`操作只触发一次[growslice](https://github.com/golang/go/blob/f21be2fdc6f1becdbed1592ea0b245cdeedc5ac8/src/runtime/slice.go#L125)，并且`old.len` == `old.cap` == 0。对于上面的代码而言，这个改动不会改变`growslice`的行为。

**Comment by 51snail** [comment]
应该是1.16的`class_to_size`发生了变化，新增了24，1.15`var class_to_size =  [_NumSizeClasses]uint16{0, 8, 16, 32...`，1.16` var class_to_size = _NumSizeClasses]uint16{0, 8, 16, 24, 32,...` ， int64 占用 8 byte，总内存 正好3 * 8 = 24 byte。
