### ISSUE TITLE
[勘误]反馈一个第1章第3节的问题

### ISSUE THREAD

**Issue by backendTime-coder** [RainbowMango/GoExpertProgramming#93]
**问题描述**
hmap.bucket为数组指针，数组的大小为2^B，例如：hmap.B=2， 而hmap.buckets长度是2^B为4

在**增量扩容**内容当中，这个 B=1, 应该是 B=0 吧，不然应该是有两个bucket
![image](https://user-images.githubusercontent.com/13270229/123384054-80700d00-d5c6-11eb-9487-6d0a6185a22c.png)

还有这个地方，这个 B=2 , 应该是 B=1 
![image](https://user-images.githubusercontent.com/13270229/123384277-c9c05c80-d5c6-11eb-9174-73b88739b98e.png)

希望大佬解答疑惑

**Comment by RainbowMango** [comment]
> 在增量扩容内容当中，这个 B=1, 应该是 B=0 吧，不然应该是有两个bucket

是的，你说得对。看得很细，赞一个！
issue先开着，回头我改完再关，谢谢。

**Comment by RainbowMango** [comment]
已经修改，马上同步给出版社。再次感谢。

修改后的配图如下。
![image](https://user-images.githubusercontent.com/8268873/129717602-9d41a18b-6192-42f0-b2ac-84956eb9ae24.png)

![image](https://user-images.githubusercontent.com/8268873/129717620-d0ff7f97-63b1-4ff8-ac56-dc0690fbca7a.png)

**Comment by backendTime-coder** [comment]
辛苦大佬~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hongcai ***@***.***&gt;; 
发送时间: 2021年8月17日(星期二) 晚上7:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [RainbowMango/GoExpertProgramming] [勘误]反馈一个第1章第3节的问题 (#93)





 
已经修改，马上同步给出版社。再次感谢。
 
修改后的配图如下。
