### ISSUE TITLE
[勘误]反馈一个第1章第2节，关于切片简单表达式的 cap 取值问题

### ISSUE THREAD

**Issue by callmePicacho** [RainbowMango/GoExpertProgramming#96]
**问题描述**
切片的简单表达式中 cap 值计算表达式有误

**如何找到这个错误**
- 章节：第1章第2节，1.2.4 切片表达->1.简单表达式->1)底层数组共享
- 页码：P22

**您认为应该如何？**
在书中写道：
> 新切片的生成逻辑可以使用以下伪代码表示：
```go
b.array = &a[low]
b.len = high - low
b.cap = len(a) - low
```

应该是：`b.cap = cap(a) - low` ，b 的 cap 是由 a 的 cap 而不是 len 计算出来的

**图片**
如果有可能，尽量提供图片。
![image](https://user-images.githubusercontent.com/38685653/129487483-e90a37d8-0bd6-4598-bfed-44974dc32906.png)

**其他补充信息**

**Comment by RainbowMango** [comment]
非常感谢~ Right. 马上修改。

**Comment by RainbowMango** [comment]
```diff
-b.cap = len(a) - low
+b.cap = cap(a) - low
```

已修改。稍后会同步给出版社，应该会在第四次印刷时修订。
