### ISSUE TITLE
[勘误]反馈一个第1章第3节的错别字

### ISSUE THREAD

**Issue by callmePicacho** [RainbowMango/GoExpertProgramming#97]
**问题描述**
哈希冲突解决错误描述有误

**如何找到这个错误**
- 章节：1 章 3 节 -> 1.3.3 实现原理 -> 2. Hash 冲突
- 页码：P30

**您认为应该如何？**
原句："由于每个 bucket 可以存放 8 个键值对，所以同一个 bucket 存放超过 8 个键值对时就会再创建一个键值对，用类似链表的方式将 bucket 连接起来"
认为有误的地方："同一个 bucket 存放超过 8 个键值对时就会再创建一个 bucket？"，创建的是 bucket，通过 overflow 指针连起来，而不是再创建一个"键值对"吧？

**图片**
如果有可能，尽量提供图片。

**其他补充信息**

**Comment by RainbowMango** [comment]
非常感谢。你是对的。

**Comment by RainbowMango** [comment]
已修改，稍后会同步给出版社。不出意外将会在第四次印刷时包含该修订。再次感谢~
```diff
-由于每个bucket可以存放8个键值对，所以同一个bucket存放超过8个键值对时就会再创建一个键值对，用类似链表的方式将bucket连接起来。
+由于每个bucket可以存放8个键值对，所以同一个bucket存放超过8个键值对时就会再创建一个bucket，用类似链表的方式将bucket连接起来。
```
